#:schema https://raw.githubusercontent.com/robgonnella/releasaurus/refs/heads/main/schema/schema.json

[changelog]
skip_ci = true
skip_chore = true
reword = [
  { sha = "d16f5ab4", message = "ci: bump ci versions" }
]

[[package]]
name = "r-lanscan"
release_type = "rust"

[[package]]
name = "r-lanlib"
release_type = "rust"
workspace_root = "."
path = "lib"
tag_prefix = "v"

[[package]]
name = "r-lancli"
release_type = "rust"
workspace_root = "."
path = "cli"
tag_prefix = "v"

[[package]]
name = "r-lanterm"
release_type = "rust"
workspace_root = "."
path = "term"
tag_prefix = "v"
