#:schema https://raw.githubusercontent.com/robgonnella/releasaurus/refs/heads/main/schema/schema.json

[changelog]
skip_ci = true
skip_chore = true
reword = [
  { sha = "d16f5ab4", message = "ci: bump ci versions" }
]

[[package]]
name = "r-lancli"
path = "cli"
tag_prefix = "r-lancli-v"
release_type = "rust"

[[package]]
name = "r-lanlib"
path = "lib"
tag_prefix = "r-lanlib-v"
release_type = "rust"

[[package]]
name = "r-lanterm"
path = "term"
tag_prefix = "r-lanterm-v"
release_type = "rust"
