#:schema https://raw.githubusercontent.com/robgonnella/releasaurus/refs/heads/main/schema/schema.json

[changelog]
skip_ci = true
skip_chore = true
reword = [
  { sha = "d16f5ab4", message = "ci: bump ci versions" }
]

[[package]]
name = "r-lancli"
path = "cli"
release_type = "rust"
additional_paths = ["."]

[[package]]
name = "r-lanlib"
path = "lib"
release_type = "rust"
additional_paths = ["."]

[[package]]
name = "r-lanterm"
path = "term"
release_type = "rust"
additional_paths = ["."]
