# schema: ../releasaurus/schema/schema.json

[changelog]
skip_ci = true
skip_chore = true
reword = [
  { sha = "d16f5ab4", message = "ci: bump ci versions" }
]

[[package]]
release_type = "rust"
tag_prefix = "v"
sub_packages = [
  { name = "r-lancli", path = "cli", release_type = "rust" },
  { name = "r-lanlib", path = "lib", release_type = "rust" },
  { name = "r-lanterm", path = "term", release_type = "rust" },
]
