name: gh-release

on:
  push:
    branches: ["main"]

jobs:
  releasaurus:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: robgonnella/releasaurus/action@v0.10.1
        with:
          command: release
          command_args: >-
            --forge github
            --repo ${{ github.server_url}}/${{ github.repository }}
            --token ${{ secrets.RELEASE_TOKEN }}
            --debug
      - uses: robgonnella/releasaurus/action@v0.10.1
        with:
          command: release-pr
          command_args: >-
            --forge github
            --repo ${{ github.server_url}}/${{ github.repository }}
            --token ${{ secrets.RELEASE_TOKEN }}
            --debug
